# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class AttendanceType(object):
    Basic = 0
    Event = 1
    Newbie = 2
    EventCountDown = 3
    Event20Days = 4

