# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BGMUIExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BGMUIExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBGMUIExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BGMUIExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BGMUIExcel
    def UIPrefab(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def BGMId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def BGMId2nd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def BGMId3rd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(5)
def BGMUIExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddUIPrefab(builder, UIPrefab): builder.PrependUint32Slot(0, UIPrefab, 0)
def BGMUIExcelAddUIPrefab(builder, UIPrefab):
    """This method is deprecated. Please switch to AddUIPrefab."""
    return AddUIPrefab(builder, UIPrefab)
def AddBGMId(builder, BGMId): builder.PrependInt64Slot(1, BGMId, 0)
def BGMUIExcelAddBGMId(builder, BGMId):
    """This method is deprecated. Please switch to AddBGMId."""
    return AddBGMId(builder, BGMId)
def AddBGMId2nd(builder, BGMId2nd): builder.PrependInt64Slot(2, BGMId2nd, 0)
def BGMUIExcelAddBGMId2nd(builder, BGMId2nd):
    """This method is deprecated. Please switch to AddBGMId2nd."""
    return AddBGMId2nd(builder, BGMId2nd)
def AddBGMId3rd(builder, BGMId3rd): builder.PrependInt64Slot(3, BGMId3rd, 0)
def BGMUIExcelAddBGMId3rd(builder, BGMId3rd):
    """This method is deprecated. Please switch to AddBGMId3rd."""
    return AddBGMId3rd(builder, BGMId3rd)
def AddEventContentId(builder, EventContentId): builder.PrependInt64Slot(4, EventContentId, 0)
def BGMUIExcelAddEventContentId(builder, EventContentId):
    """This method is deprecated. Please switch to AddEventContentId."""
    return AddEventContentId(builder, EventContentId)
def End(builder): return builder.EndObject()
def BGMUIExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)