# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CharacterVictoryInteractionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CharacterVictoryInteractionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCharacterVictoryInteractionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CharacterVictoryInteractionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CharacterVictoryInteractionExcel
    def InteractionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def CostumeId01(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex01(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath01(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath01(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def CostumeId02(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex02(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath02(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath02(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def CostumeId03(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex03(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath03(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath03(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def CostumeId04(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex04(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath04(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath04(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def CostumeId05(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex05(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath05(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath05(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def CostumeId06(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def PositionIndex06(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterVictoryInteractionExcel
    def VictoryStartAnimationPath06(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVictoryInteractionExcel
    def VictoryEndAnimationPath06(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(25)
def CharacterVictoryInteractionExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddInteractionId(builder, InteractionId): builder.PrependInt64Slot(0, InteractionId, 0)
def CharacterVictoryInteractionExcelAddInteractionId(builder, InteractionId):
    """This method is deprecated. Please switch to AddInteractionId."""
    return AddInteractionId(builder, InteractionId)
def AddCostumeId01(builder, CostumeId01): builder.PrependInt64Slot(1, CostumeId01, 0)
def CharacterVictoryInteractionExcelAddCostumeId01(builder, CostumeId01):
    """This method is deprecated. Please switch to AddCostumeId01."""
    return AddCostumeId01(builder, CostumeId01)
def AddPositionIndex01(builder, PositionIndex01): builder.PrependInt32Slot(2, PositionIndex01, 0)
def CharacterVictoryInteractionExcelAddPositionIndex01(builder, PositionIndex01):
    """This method is deprecated. Please switch to AddPositionIndex01."""
    return AddPositionIndex01(builder, PositionIndex01)
def AddVictoryStartAnimationPath01(builder, VictoryStartAnimationPath01): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath01), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath01(builder, VictoryStartAnimationPath01):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath01."""
    return AddVictoryStartAnimationPath01(builder, VictoryStartAnimationPath01)
def AddVictoryEndAnimationPath01(builder, VictoryEndAnimationPath01): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath01), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath01(builder, VictoryEndAnimationPath01):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath01."""
    return AddVictoryEndAnimationPath01(builder, VictoryEndAnimationPath01)
def AddCostumeId02(builder, CostumeId02): builder.PrependInt64Slot(5, CostumeId02, 0)
def CharacterVictoryInteractionExcelAddCostumeId02(builder, CostumeId02):
    """This method is deprecated. Please switch to AddCostumeId02."""
    return AddCostumeId02(builder, CostumeId02)
def AddPositionIndex02(builder, PositionIndex02): builder.PrependInt32Slot(6, PositionIndex02, 0)
def CharacterVictoryInteractionExcelAddPositionIndex02(builder, PositionIndex02):
    """This method is deprecated. Please switch to AddPositionIndex02."""
    return AddPositionIndex02(builder, PositionIndex02)
def AddVictoryStartAnimationPath02(builder, VictoryStartAnimationPath02): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath02), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath02(builder, VictoryStartAnimationPath02):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath02."""
    return AddVictoryStartAnimationPath02(builder, VictoryStartAnimationPath02)
def AddVictoryEndAnimationPath02(builder, VictoryEndAnimationPath02): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath02), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath02(builder, VictoryEndAnimationPath02):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath02."""
    return AddVictoryEndAnimationPath02(builder, VictoryEndAnimationPath02)
def AddCostumeId03(builder, CostumeId03): builder.PrependInt64Slot(9, CostumeId03, 0)
def CharacterVictoryInteractionExcelAddCostumeId03(builder, CostumeId03):
    """This method is deprecated. Please switch to AddCostumeId03."""
    return AddCostumeId03(builder, CostumeId03)
def AddPositionIndex03(builder, PositionIndex03): builder.PrependInt32Slot(10, PositionIndex03, 0)
def CharacterVictoryInteractionExcelAddPositionIndex03(builder, PositionIndex03):
    """This method is deprecated. Please switch to AddPositionIndex03."""
    return AddPositionIndex03(builder, PositionIndex03)
def AddVictoryStartAnimationPath03(builder, VictoryStartAnimationPath03): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath03), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath03(builder, VictoryStartAnimationPath03):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath03."""
    return AddVictoryStartAnimationPath03(builder, VictoryStartAnimationPath03)
def AddVictoryEndAnimationPath03(builder, VictoryEndAnimationPath03): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath03), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath03(builder, VictoryEndAnimationPath03):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath03."""
    return AddVictoryEndAnimationPath03(builder, VictoryEndAnimationPath03)
def AddCostumeId04(builder, CostumeId04): builder.PrependInt64Slot(13, CostumeId04, 0)
def CharacterVictoryInteractionExcelAddCostumeId04(builder, CostumeId04):
    """This method is deprecated. Please switch to AddCostumeId04."""
    return AddCostumeId04(builder, CostumeId04)
def AddPositionIndex04(builder, PositionIndex04): builder.PrependInt32Slot(14, PositionIndex04, 0)
def CharacterVictoryInteractionExcelAddPositionIndex04(builder, PositionIndex04):
    """This method is deprecated. Please switch to AddPositionIndex04."""
    return AddPositionIndex04(builder, PositionIndex04)
def AddVictoryStartAnimationPath04(builder, VictoryStartAnimationPath04): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath04), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath04(builder, VictoryStartAnimationPath04):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath04."""
    return AddVictoryStartAnimationPath04(builder, VictoryStartAnimationPath04)
def AddVictoryEndAnimationPath04(builder, VictoryEndAnimationPath04): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath04), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath04(builder, VictoryEndAnimationPath04):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath04."""
    return AddVictoryEndAnimationPath04(builder, VictoryEndAnimationPath04)
def AddCostumeId05(builder, CostumeId05): builder.PrependInt64Slot(17, CostumeId05, 0)
def CharacterVictoryInteractionExcelAddCostumeId05(builder, CostumeId05):
    """This method is deprecated. Please switch to AddCostumeId05."""
    return AddCostumeId05(builder, CostumeId05)
def AddPositionIndex05(builder, PositionIndex05): builder.PrependInt32Slot(18, PositionIndex05, 0)
def CharacterVictoryInteractionExcelAddPositionIndex05(builder, PositionIndex05):
    """This method is deprecated. Please switch to AddPositionIndex05."""
    return AddPositionIndex05(builder, PositionIndex05)
def AddVictoryStartAnimationPath05(builder, VictoryStartAnimationPath05): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath05), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath05(builder, VictoryStartAnimationPath05):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath05."""
    return AddVictoryStartAnimationPath05(builder, VictoryStartAnimationPath05)
def AddVictoryEndAnimationPath05(builder, VictoryEndAnimationPath05): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath05), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath05(builder, VictoryEndAnimationPath05):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath05."""
    return AddVictoryEndAnimationPath05(builder, VictoryEndAnimationPath05)
def AddCostumeId06(builder, CostumeId06): builder.PrependInt64Slot(21, CostumeId06, 0)
def CharacterVictoryInteractionExcelAddCostumeId06(builder, CostumeId06):
    """This method is deprecated. Please switch to AddCostumeId06."""
    return AddCostumeId06(builder, CostumeId06)
def AddPositionIndex06(builder, PositionIndex06): builder.PrependInt32Slot(22, PositionIndex06, 0)
def CharacterVictoryInteractionExcelAddPositionIndex06(builder, PositionIndex06):
    """This method is deprecated. Please switch to AddPositionIndex06."""
    return AddPositionIndex06(builder, PositionIndex06)
def AddVictoryStartAnimationPath06(builder, VictoryStartAnimationPath06): builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryStartAnimationPath06), 0)
def CharacterVictoryInteractionExcelAddVictoryStartAnimationPath06(builder, VictoryStartAnimationPath06):
    """This method is deprecated. Please switch to AddVictoryStartAnimationPath06."""
    return AddVictoryStartAnimationPath06(builder, VictoryStartAnimationPath06)
def AddVictoryEndAnimationPath06(builder, VictoryEndAnimationPath06): builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(VictoryEndAnimationPath06), 0)
def CharacterVictoryInteractionExcelAddVictoryEndAnimationPath06(builder, VictoryEndAnimationPath06):
    """This method is deprecated. Please switch to AddVictoryEndAnimationPath06."""
    return AddVictoryEndAnimationPath06(builder, VictoryEndAnimationPath06)
def End(builder): return builder.EndObject()
def CharacterVictoryInteractionExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)