# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClanChattingEmojiExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClanChattingEmojiExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClanChattingEmojiExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClanChattingEmojiExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClanChattingEmojiExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def TabGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def DisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ClanChattingEmojiExcel
    def ImagePathKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClanChattingEmojiExcel
    def ImagePathJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(5)
def ClanChattingEmojiExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def ClanChattingEmojiExcelAddId(builder, Id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, Id)
def AddTabGroupId(builder, TabGroupId): builder.PrependInt32Slot(1, TabGroupId, 0)
def ClanChattingEmojiExcelAddTabGroupId(builder, TabGroupId):
    """This method is deprecated. Please switch to AddTabGroupId."""
    return AddTabGroupId(builder, TabGroupId)
def AddDisplayOrder(builder, DisplayOrder): builder.PrependInt32Slot(2, DisplayOrder, 0)
def ClanChattingEmojiExcelAddDisplayOrder(builder, DisplayOrder):
    """This method is deprecated. Please switch to AddDisplayOrder."""
    return AddDisplayOrder(builder, DisplayOrder)
def AddImagePathKr(builder, ImagePathKr): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathKr), 0)
def ClanChattingEmojiExcelAddImagePathKr(builder, ImagePathKr):
    """This method is deprecated. Please switch to AddImagePathKr."""
    return AddImagePathKr(builder, ImagePathKr)
def AddImagePathJp(builder, ImagePathJp): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathJp), 0)
def ClanChattingEmojiExcelAddImagePathJp(builder, ImagePathJp):
    """This method is deprecated. Please switch to AddImagePathJp."""
    return AddImagePathJp(builder, ImagePathJp)
def End(builder): return builder.EndObject()
def ClanChattingEmojiExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)