# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConquestErosionUnitExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConquestErosionUnitExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConquestErosionUnitExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConquestErosionUnitExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConquestErosionUnitExcel
    def TilePrefabId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def MassErosionUnitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def MassErosionUnitRotationY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConquestErosionUnitExcel
    def IndividualErosionUnitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestErosionUnitExcel
    def IndividualErosionUnitRotationY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(5)
def ConquestErosionUnitExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddTilePrefabId(builder, TilePrefabId): builder.PrependInt64Slot(0, TilePrefabId, 0)
def ConquestErosionUnitExcelAddTilePrefabId(builder, TilePrefabId):
    """This method is deprecated. Please switch to AddTilePrefabId."""
    return AddTilePrefabId(builder, TilePrefabId)
def AddMassErosionUnitId(builder, MassErosionUnitId): builder.PrependInt64Slot(1, MassErosionUnitId, 0)
def ConquestErosionUnitExcelAddMassErosionUnitId(builder, MassErosionUnitId):
    """This method is deprecated. Please switch to AddMassErosionUnitId."""
    return AddMassErosionUnitId(builder, MassErosionUnitId)
def AddMassErosionUnitRotationY(builder, MassErosionUnitRotationY): builder.PrependFloat32Slot(2, MassErosionUnitRotationY, 0.0)
def ConquestErosionUnitExcelAddMassErosionUnitRotationY(builder, MassErosionUnitRotationY):
    """This method is deprecated. Please switch to AddMassErosionUnitRotationY."""
    return AddMassErosionUnitRotationY(builder, MassErosionUnitRotationY)
def AddIndividualErosionUnitId(builder, IndividualErosionUnitId): builder.PrependInt64Slot(3, IndividualErosionUnitId, 0)
def ConquestErosionUnitExcelAddIndividualErosionUnitId(builder, IndividualErosionUnitId):
    """This method is deprecated. Please switch to AddIndividualErosionUnitId."""
    return AddIndividualErosionUnitId(builder, IndividualErosionUnitId)
def AddIndividualErosionUnitRotationY(builder, IndividualErosionUnitRotationY): builder.PrependFloat32Slot(4, IndividualErosionUnitRotationY, 0.0)
def ConquestErosionUnitExcelAddIndividualErosionUnitRotationY(builder, IndividualErosionUnitRotationY):
    """This method is deprecated. Please switch to AddIndividualErosionUnitRotationY."""
    return AddIndividualErosionUnitRotationY(builder, IndividualErosionUnitRotationY)
def End(builder): return builder.EndObject()
def ConquestErosionUnitExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)