# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConquestObjectExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConquestObjectExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConquestObjectExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConquestObjectExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConquestObjectExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def ConquestObjectType_(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConquestObjectExcel
    def PrefabName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConquestObjectExcel
    def ConquestRewardParcelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def ConquestRewardID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def ConquestRewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def Disposable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConquestObjectExcel
    def StepIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConquestObjectExcel
    def StepObjectCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(12)
def ConquestObjectExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def ConquestObjectExcelAddId(builder, Id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, Id)
def AddEventContentId(builder, EventContentId): builder.PrependInt64Slot(1, EventContentId, 0)
def ConquestObjectExcelAddEventContentId(builder, EventContentId):
    """This method is deprecated. Please switch to AddEventContentId."""
    return AddEventContentId(builder, EventContentId)
def AddConquestObjectType_(builder, ConquestObjectType_): builder.PrependInt32Slot(2, ConquestObjectType_, 0)
def ConquestObjectExcelAddConquestObjectType_(builder, ConquestObjectType_):
    """This method is deprecated. Please switch to AddConquestObjectType_."""
    return AddConquestObjectType_(builder, ConquestObjectType_)
def AddKey(builder, Key): builder.PrependUint32Slot(3, Key, 0)
def ConquestObjectExcelAddKey(builder, Key):
    """This method is deprecated. Please switch to AddKey."""
    return AddKey(builder, Key)
def AddName(builder, Name): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(Name), 0)
def ConquestObjectExcelAddName(builder, Name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, Name)
def AddPrefabName(builder, PrefabName): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(PrefabName), 0)
def ConquestObjectExcelAddPrefabName(builder, PrefabName):
    """This method is deprecated. Please switch to AddPrefabName."""
    return AddPrefabName(builder, PrefabName)
def AddConquestRewardParcelType(builder, ConquestRewardParcelType): builder.PrependInt32Slot(6, ConquestRewardParcelType, 0)
def ConquestObjectExcelAddConquestRewardParcelType(builder, ConquestRewardParcelType):
    """This method is deprecated. Please switch to AddConquestRewardParcelType."""
    return AddConquestRewardParcelType(builder, ConquestRewardParcelType)
def AddConquestRewardID(builder, ConquestRewardID): builder.PrependInt64Slot(7, ConquestRewardID, 0)
def ConquestObjectExcelAddConquestRewardID(builder, ConquestRewardID):
    """This method is deprecated. Please switch to AddConquestRewardID."""
    return AddConquestRewardID(builder, ConquestRewardID)
def AddConquestRewardAmount(builder, ConquestRewardAmount): builder.PrependInt32Slot(8, ConquestRewardAmount, 0)
def ConquestObjectExcelAddConquestRewardAmount(builder, ConquestRewardAmount):
    """This method is deprecated. Please switch to AddConquestRewardAmount."""
    return AddConquestRewardAmount(builder, ConquestRewardAmount)
def AddDisposable(builder, Disposable): builder.PrependBoolSlot(9, Disposable, 0)
def ConquestObjectExcelAddDisposable(builder, Disposable):
    """This method is deprecated. Please switch to AddDisposable."""
    return AddDisposable(builder, Disposable)
def AddStepIndex(builder, StepIndex): builder.PrependInt32Slot(10, StepIndex, 0)
def ConquestObjectExcelAddStepIndex(builder, StepIndex):
    """This method is deprecated. Please switch to AddStepIndex."""
    return AddStepIndex(builder, StepIndex)
def AddStepObjectCount(builder, StepObjectCount): builder.PrependInt32Slot(11, StepObjectCount, 0)
def ConquestObjectExcelAddStepObjectCount(builder, StepObjectCount):
    """This method is deprecated. Please switch to AddStepObjectCount."""
    return AddStepObjectCount(builder, StepObjectCount)
def End(builder): return builder.EndObject()
def ConquestObjectExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)