# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class EventContentDiceRaceNodeType(object):
    StartNode = 0
    RewardNode = 1
    MoveForwardNode = 2
    SpecialRewardNode = 3

