# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentMeetupExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentMeetupExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventContentMeetupExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventContentMeetupExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentMeetupExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentMeetupExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentMeetupExcel
    def CharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentMeetupExcel
    def ConditionScenarioGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentMeetupExcel
    def ConditionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentMeetupExcel
    def ConditionParameter(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # EventContentMeetupExcel
    def ConditionParameterAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # EventContentMeetupExcel
    def ConditionParameterLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EventContentMeetupExcel
    def ConditionParameterIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # EventContentMeetupExcel
    def ConditionPrintType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(7)
def EventContentMeetupExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def EventContentMeetupExcelAddId(builder, Id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, Id)
def AddEventContentId(builder, EventContentId): builder.PrependInt64Slot(1, EventContentId, 0)
def EventContentMeetupExcelAddEventContentId(builder, EventContentId):
    """This method is deprecated. Please switch to AddEventContentId."""
    return AddEventContentId(builder, EventContentId)
def AddCharacterId(builder, CharacterId): builder.PrependInt64Slot(2, CharacterId, 0)
def EventContentMeetupExcelAddCharacterId(builder, CharacterId):
    """This method is deprecated. Please switch to AddCharacterId."""
    return AddCharacterId(builder, CharacterId)
def AddConditionScenarioGroupId(builder, ConditionScenarioGroupId): builder.PrependInt64Slot(3, ConditionScenarioGroupId, 0)
def EventContentMeetupExcelAddConditionScenarioGroupId(builder, ConditionScenarioGroupId):
    """This method is deprecated. Please switch to AddConditionScenarioGroupId."""
    return AddConditionScenarioGroupId(builder, ConditionScenarioGroupId)
def AddConditionType(builder, ConditionType): builder.PrependInt32Slot(4, ConditionType, 0)
def EventContentMeetupExcelAddConditionType(builder, ConditionType):
    """This method is deprecated. Please switch to AddConditionType."""
    return AddConditionType(builder, ConditionType)
def AddConditionParameter(builder, ConditionParameter): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ConditionParameter), 0)
def EventContentMeetupExcelAddConditionParameter(builder, ConditionParameter):
    """This method is deprecated. Please switch to AddConditionParameter."""
    return AddConditionParameter(builder, ConditionParameter)
def StartConditionParameterVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def EventContentMeetupExcelStartConditionParameterVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartConditionParameterVector(builder, numElems)
def AddConditionPrintType(builder, ConditionPrintType): builder.PrependInt32Slot(6, ConditionPrintType, 0)
def EventContentMeetupExcelAddConditionPrintType(builder, ConditionPrintType):
    """This method is deprecated. Please switch to AddConditionPrintType."""
    return AddConditionPrintType(builder, ConditionPrintType)
def End(builder): return builder.EndObject()
def EventContentMeetupExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)