# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldMasteryManageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldMasteryManageExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldMasteryManageExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldMasteryManageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldMasteryManageExcel
    def FieldSeason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldMasteryManageExcel
    def LocalizeEtc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FieldMasteryManageExcel
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldMasteryManageExcel
    def LevelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(4)
def FieldMasteryManageExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddFieldSeason(builder, FieldSeason): builder.PrependInt64Slot(0, FieldSeason, 0)
def FieldMasteryManageExcelAddFieldSeason(builder, FieldSeason):
    """This method is deprecated. Please switch to AddFieldSeason."""
    return AddFieldSeason(builder, FieldSeason)
def AddLocalizeEtc(builder, LocalizeEtc): builder.PrependUint32Slot(1, LocalizeEtc, 0)
def FieldMasteryManageExcelAddLocalizeEtc(builder, LocalizeEtc):
    """This method is deprecated. Please switch to AddLocalizeEtc."""
    return AddLocalizeEtc(builder, LocalizeEtc)
def AddImagePath(builder, ImagePath): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePath), 0)
def FieldMasteryManageExcelAddImagePath(builder, ImagePath):
    """This method is deprecated. Please switch to AddImagePath."""
    return AddImagePath(builder, ImagePath)
def AddLevelId(builder, LevelId): builder.PrependInt64Slot(3, LevelId, 0)
def FieldMasteryManageExcelAddLevelId(builder, LevelId):
    """This method is deprecated. Please switch to AddLevelId."""
    return AddLevelId(builder, LevelId)
def End(builder): return builder.EndObject()
def FieldMasteryManageExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)