# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class FurnitureFunctionType(object):
    None_ = 0
    EventCollection = 1
    VideoPlay = 2
    TrophyCollection = 3
    InteractionBGMPlay = 4

