# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class GachaDisplayTag(object):
    None_ = 0
    Limited = 1
    TwoStar = 2
    ThreeStar = 3
    Free = 4
    New = 5
    Fes = 6
    SelectRecruit = 7

