# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaCraftNodeGroupExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaCraftNodeGroupExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGachaCraftNodeGroupExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GachaCraftNodeGroupExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaCraftNodeGroupExcel
    def NodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaCraftNodeGroupExcel
    def GachaGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaCraftNodeGroupExcel
    def ProbWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(3)
def GachaCraftNodeGroupExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddNodeId(builder, NodeId): builder.PrependInt64Slot(0, NodeId, 0)
def GachaCraftNodeGroupExcelAddNodeId(builder, NodeId):
    """This method is deprecated. Please switch to AddNodeId."""
    return AddNodeId(builder, NodeId)
def AddGachaGroupId(builder, GachaGroupId): builder.PrependInt64Slot(1, GachaGroupId, 0)
def GachaCraftNodeGroupExcelAddGachaGroupId(builder, GachaGroupId):
    """This method is deprecated. Please switch to AddGachaGroupId."""
    return AddGachaGroupId(builder, GachaGroupId)
def AddProbWeight(builder, ProbWeight): builder.PrependInt64Slot(2, ProbWeight, 0)
def GachaCraftNodeGroupExcelAddProbWeight(builder, ProbWeight):
    """This method is deprecated. Please switch to AddProbWeight."""
    return AddProbWeight(builder, ProbWeight)
def End(builder): return builder.EndObject()
def GachaCraftNodeGroupExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)