# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GuideMissionOpenStageConditionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GuideMissionOpenStageConditionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGuideMissionOpenStageConditionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GuideMissionOpenStageConditionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GuideMissionOpenStageConditionExcel
    def SeasonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GuideMissionOpenStageConditionExcel
    def OrderNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GuideMissionOpenStageConditionExcel
    def TabLocalizeCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionOpenStageConditionExcel
    def ClearScenarioModeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GuideMissionOpenStageConditionExcel
    def LockScenarioTextLocailzeCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionOpenStageConditionExcel
    def ShortcutScenarioUI(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionOpenStageConditionExcel
    def ClearStageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GuideMissionOpenStageConditionExcel
    def LockStageTextLocailzeCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionOpenStageConditionExcel
    def ShortcutStageUI(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(9)
def GuideMissionOpenStageConditionExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSeasonId(builder, SeasonId): builder.PrependInt64Slot(0, SeasonId, 0)
def GuideMissionOpenStageConditionExcelAddSeasonId(builder, SeasonId):
    """This method is deprecated. Please switch to AddSeasonId."""
    return AddSeasonId(builder, SeasonId)
def AddOrderNumber(builder, OrderNumber): builder.PrependInt64Slot(1, OrderNumber, 0)
def GuideMissionOpenStageConditionExcelAddOrderNumber(builder, OrderNumber):
    """This method is deprecated. Please switch to AddOrderNumber."""
    return AddOrderNumber(builder, OrderNumber)
def AddTabLocalizeCode(builder, TabLocalizeCode): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(TabLocalizeCode), 0)
def GuideMissionOpenStageConditionExcelAddTabLocalizeCode(builder, TabLocalizeCode):
    """This method is deprecated. Please switch to AddTabLocalizeCode."""
    return AddTabLocalizeCode(builder, TabLocalizeCode)
def AddClearScenarioModeId(builder, ClearScenarioModeId): builder.PrependInt64Slot(3, ClearScenarioModeId, 0)
def GuideMissionOpenStageConditionExcelAddClearScenarioModeId(builder, ClearScenarioModeId):
    """This method is deprecated. Please switch to AddClearScenarioModeId."""
    return AddClearScenarioModeId(builder, ClearScenarioModeId)
def AddLockScenarioTextLocailzeCode(builder, LockScenarioTextLocailzeCode): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(LockScenarioTextLocailzeCode), 0)
def GuideMissionOpenStageConditionExcelAddLockScenarioTextLocailzeCode(builder, LockScenarioTextLocailzeCode):
    """This method is deprecated. Please switch to AddLockScenarioTextLocailzeCode."""
    return AddLockScenarioTextLocailzeCode(builder, LockScenarioTextLocailzeCode)
def AddShortcutScenarioUI(builder, ShortcutScenarioUI): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ShortcutScenarioUI), 0)
def GuideMissionOpenStageConditionExcelAddShortcutScenarioUI(builder, ShortcutScenarioUI):
    """This method is deprecated. Please switch to AddShortcutScenarioUI."""
    return AddShortcutScenarioUI(builder, ShortcutScenarioUI)
def AddClearStageId(builder, ClearStageId): builder.PrependInt64Slot(6, ClearStageId, 0)
def GuideMissionOpenStageConditionExcelAddClearStageId(builder, ClearStageId):
    """This method is deprecated. Please switch to AddClearStageId."""
    return AddClearStageId(builder, ClearStageId)
def AddLockStageTextLocailzeCode(builder, LockStageTextLocailzeCode): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(LockStageTextLocailzeCode), 0)
def GuideMissionOpenStageConditionExcelAddLockStageTextLocailzeCode(builder, LockStageTextLocailzeCode):
    """This method is deprecated. Please switch to AddLockStageTextLocailzeCode."""
    return AddLockStageTextLocailzeCode(builder, LockStageTextLocailzeCode)
def AddShortcutStageUI(builder, ShortcutStageUI): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(ShortcutStageUI), 0)
def GuideMissionOpenStageConditionExcelAddShortcutStageUI(builder, ShortcutStageUI):
    """This method is deprecated. Please switch to AddShortcutStageUI."""
    return AddShortcutStageUI(builder, ShortcutStageUI)
def End(builder): return builder.EndObject()
def GuideMissionOpenStageConditionExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)