# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoadingImageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoadingImageExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoadingImageExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoadingImageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoadingImageExcel
    def ID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # LoadingImageExcel
    def ImagePathKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoadingImageExcel
    def ImagePathJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LoadingImageExcel
    def DisplayWeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(4)
def LoadingImageExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddID(builder, ID): builder.PrependInt64Slot(0, ID, 0)
def LoadingImageExcelAddID(builder, ID):
    """This method is deprecated. Please switch to AddID."""
    return AddID(builder, ID)
def AddImagePathKr(builder, ImagePathKr): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathKr), 0)
def LoadingImageExcelAddImagePathKr(builder, ImagePathKr):
    """This method is deprecated. Please switch to AddImagePathKr."""
    return AddImagePathKr(builder, ImagePathKr)
def AddImagePathJp(builder, ImagePathJp): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePathJp), 0)
def LoadingImageExcelAddImagePathJp(builder, ImagePathJp):
    """This method is deprecated. Please switch to AddImagePathJp."""
    return AddImagePathJp(builder, ImagePathJp)
def AddDisplayWeight(builder, DisplayWeight): builder.PrependInt32Slot(3, DisplayWeight, 0)
def LoadingImageExcelAddDisplayWeight(builder, DisplayWeight):
    """This method is deprecated. Please switch to AddDisplayWeight."""
    return AddDisplayWeight(builder, DisplayWeight)
def End(builder): return builder.EndObject()
def LoadingImageExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)