# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizeErrorExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizeErrorExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLocalizeErrorExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LocalizeErrorExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizeErrorExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LocalizeErrorExcel
    def ErrorLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LocalizeErrorExcel
    def Kr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeErrorExcel
    def Jp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def LocalizeErrorExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddKey(builder, Key): builder.PrependUint32Slot(0, Key, 0)
def LocalizeErrorExcelAddKey(builder, Key):
    """This method is deprecated. Please switch to AddKey."""
    return AddKey(builder, Key)
def AddErrorLevel(builder, ErrorLevel): builder.PrependInt32Slot(1, ErrorLevel, 0)
def LocalizeErrorExcelAddErrorLevel(builder, ErrorLevel):
    """This method is deprecated. Please switch to AddErrorLevel."""
    return AddErrorLevel(builder, ErrorLevel)
def AddKr(builder, Kr): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(Kr), 0)
def LocalizeErrorExcelAddKr(builder, Kr):
    """This method is deprecated. Please switch to AddKr."""
    return AddKr(builder, Kr)
def AddJp(builder, Jp): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(Jp), 0)
def LocalizeErrorExcelAddJp(builder, Jp):
    """This method is deprecated. Please switch to AddJp."""
    return AddJp(builder, Jp)
def End(builder): return builder.EndObject()
def LocalizeErrorExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)