# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MinigameTBGObjectExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MinigameTBGObjectExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMinigameTBGObjectExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MinigameTBGObjectExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MinigameTBGObjectExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGObjectExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGObjectExcel
    def PrefabName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameTBGObjectExcel
    def ObjectType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGObjectExcel
    def ObjectCostType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGObjectExcel
    def ObjectCostId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGObjectExcel
    def ObjectCostAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameTBGObjectExcel
    def Disposable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameTBGObjectExcel
    def ReEncounterCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(9)
def MinigameTBGObjectExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddUniqueId(builder, UniqueId): builder.PrependInt64Slot(0, UniqueId, 0)
def MinigameTBGObjectExcelAddUniqueId(builder, UniqueId):
    """This method is deprecated. Please switch to AddUniqueId."""
    return AddUniqueId(builder, UniqueId)
def AddKey(builder, Key): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Key), 0)
def MinigameTBGObjectExcelAddKey(builder, Key):
    """This method is deprecated. Please switch to AddKey."""
    return AddKey(builder, Key)
def AddPrefabName(builder, PrefabName): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(PrefabName), 0)
def MinigameTBGObjectExcelAddPrefabName(builder, PrefabName):
    """This method is deprecated. Please switch to AddPrefabName."""
    return AddPrefabName(builder, PrefabName)
def AddObjectType(builder, ObjectType): builder.PrependInt32Slot(3, ObjectType, 0)
def MinigameTBGObjectExcelAddObjectType(builder, ObjectType):
    """This method is deprecated. Please switch to AddObjectType."""
    return AddObjectType(builder, ObjectType)
def AddObjectCostType(builder, ObjectCostType): builder.PrependInt32Slot(4, ObjectCostType, 0)
def MinigameTBGObjectExcelAddObjectCostType(builder, ObjectCostType):
    """This method is deprecated. Please switch to AddObjectCostType."""
    return AddObjectCostType(builder, ObjectCostType)
def AddObjectCostId(builder, ObjectCostId): builder.PrependInt64Slot(5, ObjectCostId, 0)
def MinigameTBGObjectExcelAddObjectCostId(builder, ObjectCostId):
    """This method is deprecated. Please switch to AddObjectCostId."""
    return AddObjectCostId(builder, ObjectCostId)
def AddObjectCostAmount(builder, ObjectCostAmount): builder.PrependInt32Slot(6, ObjectCostAmount, 0)
def MinigameTBGObjectExcelAddObjectCostAmount(builder, ObjectCostAmount):
    """This method is deprecated. Please switch to AddObjectCostAmount."""
    return AddObjectCostAmount(builder, ObjectCostAmount)
def AddDisposable(builder, Disposable): builder.PrependBoolSlot(7, Disposable, 0)
def MinigameTBGObjectExcelAddDisposable(builder, Disposable):
    """This method is deprecated. Please switch to AddDisposable."""
    return AddDisposable(builder, Disposable)
def AddReEncounterCost(builder, ReEncounterCost): builder.PrependBoolSlot(8, ReEncounterCost, 0)
def MinigameTBGObjectExcelAddReEncounterCost(builder, ReEncounterCost):
    """This method is deprecated. Please switch to AddReEncounterCost."""
    return AddReEncounterCost(builder, ReEncounterCost)
def End(builder): return builder.EndObject()
def MinigameTBGObjectExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)