# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class MiniGameTBGThemaRewardType(object):
    TreasureReward = 0
    EmptyTreasureReward = 1
    HiddenThemaTreasureReward = 2

