# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopFreeRecruitPeriodExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopFreeRecruitPeriodExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopFreeRecruitPeriodExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopFreeRecruitPeriodExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopFreeRecruitPeriodExcel
    def ShopFreeRecruitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitPeriodExcel
    def ShopFreeRecruitIntervalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitPeriodExcel
    def IntervalDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitPeriodExcel
    def FreeRecruitCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(4)
def ShopFreeRecruitPeriodExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddShopFreeRecruitId(builder, ShopFreeRecruitId): builder.PrependInt64Slot(0, ShopFreeRecruitId, 0)
def ShopFreeRecruitPeriodExcelAddShopFreeRecruitId(builder, ShopFreeRecruitId):
    """This method is deprecated. Please switch to AddShopFreeRecruitId."""
    return AddShopFreeRecruitId(builder, ShopFreeRecruitId)
def AddShopFreeRecruitIntervalId(builder, ShopFreeRecruitIntervalId): builder.PrependInt64Slot(1, ShopFreeRecruitIntervalId, 0)
def ShopFreeRecruitPeriodExcelAddShopFreeRecruitIntervalId(builder, ShopFreeRecruitIntervalId):
    """This method is deprecated. Please switch to AddShopFreeRecruitIntervalId."""
    return AddShopFreeRecruitIntervalId(builder, ShopFreeRecruitIntervalId)
def AddIntervalDate(builder, IntervalDate): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(IntervalDate), 0)
def ShopFreeRecruitPeriodExcelAddIntervalDate(builder, IntervalDate):
    """This method is deprecated. Please switch to AddIntervalDate."""
    return AddIntervalDate(builder, IntervalDate)
def AddFreeRecruitCount(builder, FreeRecruitCount): builder.PrependInt32Slot(3, FreeRecruitCount, 0)
def ShopFreeRecruitPeriodExcelAddFreeRecruitCount(builder, FreeRecruitCount):
    """This method is deprecated. Please switch to AddFreeRecruitCount."""
    return AddFreeRecruitCount(builder, FreeRecruitCount)
def End(builder): return builder.EndObject()
def ShopFreeRecruitPeriodExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)