# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopFreeRecruitExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopFreeRecruitExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopFreeRecruitExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopFreeRecruitExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopFreeRecruitExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitExcel
    def FreeRecruitPeriodFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def FreeRecruitPeriodTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def FreeRecruitType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitExcel
    def FreeRecruitDecorationImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def ShopRecruitId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def Start(builder): builder.StartObject(6)
def ShopFreeRecruitExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, Id): builder.PrependInt64Slot(0, Id, 0)
def ShopFreeRecruitExcelAddId(builder, Id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, Id)
def AddFreeRecruitPeriodFrom(builder, FreeRecruitPeriodFrom): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(FreeRecruitPeriodFrom), 0)
def ShopFreeRecruitExcelAddFreeRecruitPeriodFrom(builder, FreeRecruitPeriodFrom):
    """This method is deprecated. Please switch to AddFreeRecruitPeriodFrom."""
    return AddFreeRecruitPeriodFrom(builder, FreeRecruitPeriodFrom)
def AddFreeRecruitPeriodTo(builder, FreeRecruitPeriodTo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(FreeRecruitPeriodTo), 0)
def ShopFreeRecruitExcelAddFreeRecruitPeriodTo(builder, FreeRecruitPeriodTo):
    """This method is deprecated. Please switch to AddFreeRecruitPeriodTo."""
    return AddFreeRecruitPeriodTo(builder, FreeRecruitPeriodTo)
def AddFreeRecruitType(builder, FreeRecruitType): builder.PrependInt32Slot(3, FreeRecruitType, 0)
def ShopFreeRecruitExcelAddFreeRecruitType(builder, FreeRecruitType):
    """This method is deprecated. Please switch to AddFreeRecruitType."""
    return AddFreeRecruitType(builder, FreeRecruitType)
def AddFreeRecruitDecorationImagePath(builder, FreeRecruitDecorationImagePath): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(FreeRecruitDecorationImagePath), 0)
def ShopFreeRecruitExcelAddFreeRecruitDecorationImagePath(builder, FreeRecruitDecorationImagePath):
    """This method is deprecated. Please switch to AddFreeRecruitDecorationImagePath."""
    return AddFreeRecruitDecorationImagePath(builder, FreeRecruitDecorationImagePath)
def AddShopRecruitId(builder, ShopRecruitId): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ShopRecruitId), 0)
def ShopFreeRecruitExcelAddShopRecruitId(builder, ShopRecruitId):
    """This method is deprecated. Please switch to AddShopRecruitId."""
    return AddShopRecruitId(builder, ShopRecruitId)
def StartShopRecruitIdVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def ShopFreeRecruitExcelStartShopRecruitIdVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartShopRecruitIdVector(builder, numElems)
def End(builder): return builder.EndObject()
def ShopFreeRecruitExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)