# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkillAdditionalTooltipExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkillAdditionalTooltipExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkillAdditionalTooltipExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkillAdditionalTooltipExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkillAdditionalTooltipExcel
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SkillAdditionalTooltipExcel
    def AdditionalSkillGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SkillAdditionalTooltipExcel
    def ShowSkillSlot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(3)
def SkillAdditionalTooltipExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddGroupId(builder, GroupId): builder.PrependInt64Slot(0, GroupId, 0)
def SkillAdditionalTooltipExcelAddGroupId(builder, GroupId):
    """This method is deprecated. Please switch to AddGroupId."""
    return AddGroupId(builder, GroupId)
def AddAdditionalSkillGroupId(builder, AdditionalSkillGroupId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(AdditionalSkillGroupId), 0)
def SkillAdditionalTooltipExcelAddAdditionalSkillGroupId(builder, AdditionalSkillGroupId):
    """This method is deprecated. Please switch to AddAdditionalSkillGroupId."""
    return AddAdditionalSkillGroupId(builder, AdditionalSkillGroupId)
def AddShowSkillSlot(builder, ShowSkillSlot): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ShowSkillSlot), 0)
def SkillAdditionalTooltipExcelAddShowSkillSlot(builder, ShowSkillSlot):
    """This method is deprecated. Please switch to AddShowSkillSlot."""
    return AddShowSkillSlot(builder, ShowSkillSlot)
def End(builder): return builder.EndObject()
def SkillAdditionalTooltipExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)