# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class TBGItemEffectType(object):
    None_ = 0
    PermanentContinuity = 1
    TemporaryContinuation = 2
    Immediately = 3

